### ISSUE TITLE
Arch ASM ?

### ISSUE THREAD

**Issue by edouard-sn** [anpawo/anpawo#1]
Please tell me more about the implication of the Arch Linux logo in your ASM's svg ?

https://github.com/anpawo/anpawo/blob/main/icons/assembly.svg

source: https://archlinux.org/

**Comment by anpawo** [comment]
c le logo de l'extension asm de vscode.
je ne savais meme pas qu'il était issue de celui de arch linux.
je vais refaire un printf en asm, comme ça jaurais mérité ce logo dans ma bio.
et aussi, jsp si je dois partir du principe que je maitrise le C apres ce qu'on a pu faire ou pas. j'ai limpression que j'ai bien fouillé la base du C pour en connaitre beaucoup de chose. je me demande qu'est ce qu'il me manque.
